version: 0.2

env: 
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "{{S3_bucket_url}}"
        BUILD_FOLDERS: "dist"
phases:
  install:  
    runtime-versiones:
        nodejs: 16
    commands:
        - echo Installing source NPM dependencies...
        - n 18
        - npm install 
        - npm install -g @angular/cli
  build:
    commands:
        - echo Build started
        - ng build
artifacts: 
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
    